### ISSUE TITLE
`otto build` - Error building app with exit status 1

### ISSUE THREAD

**Issue by njdevils9** [hashicorp/otto#272] opened 2015-10-23 18:36 UTC
When I try running `otto build` on my machine I receive the following. I am following the otto-getting-started guide but I can't seem to figure out how to fix this.. I am running Fedora 22. Any ideas?

`otto build`
`==> Detecting infrastructure credentials for: otto-getting-started (aws)`
    `Cached and encrypted infrastructure credentials found.`
    `Otto will now ask you for the password to decrypt these`
    `credentials.`
    
`Encrypted Credentials Password`
  `Infrastructure credentials are required for this operation. Otto found`
  `saved credentials that are password protected. Please enter the password`
  `to decrypt these credentials. You may also just hit <enter> and leave`
  `the password blank to force Otto to ask for the credentials again.`

 ` Enter a value:` 
`==> Querying infrastructure data for build...`
`==> Building deployment archive...`
`==> Building deployment artifact with Packer...`
 `   Raw Packer output will begin streaming in below. Otto`
 `   does not create this output. It is mirrored directly from`
`    Packer while the build is being run.`
    
`otto output will be in this color.`

`==> otto: Prevalidating AMI Name...`
`==> otto: Inspecting the source AMI...`
`==> otto: Creating temporary keypair: packer 562a7c8a-27e8-8d26-59ef-ffc520ba93b2`
`==> otto: Creating temporary security group for this instance...`
`==> otto: VPCIdNotSpecified: No default VPC for this user`
`==> otto: 	status code: 400, request id: [ ]`
`==> otto: Deleting temporary keypair...`
`Build 'otto' errored: VPCIdNotSpecified: No default VPC for this user`
	`status code: 400, request id: [ ]`
`--> otto: VPCIdNotSpecified: No default VPC for this user`
	`status code: 400, request id: [ ]`

`==> Builds finished but no artifacts were created.`
`Error building app: Error executing Packer: exit status 1`

`The error messages from Packer are usually very informative.`
`Please read it carefully and fix any issues it mentions. If`
`the message isn't clear, please report this to the Otto project.>`

**Comment by themccallister** [comment] 2015-11-06 05:37
I'm also received a very similar error.

```
Build 'otto' errored: Script exited with non-zero exit status: 100
Error building app: Error executing Packer: exit status 1

The error messages from Packer are usually very informative.
Please read it carefully and fix any issues it mentions. If
the message isn't clear, please report this to the Otto project.
```

I'm working on a PHP application deploying to AWS simple infra. 

You can find a complete screenshot attached here: 
![screenshot 2015-11-05 21 36 17](https://cloud.githubusercontent.com/assets/5354908/10990186/58f50668-8405-11e5-9f58-fe61d05bced1.png)

**Comment by brianjhanson** [comment] 2015-11-06 18:47
+1 Same issue over here.

**Comment by joshRpowell** [comment] 2015-11-21 00:45
+1 same issue 
````
➜  otto-getting-started git:(master) ✗ otto build
==> Detecting infrastructure credentials for: otto-getting-started (aws)
    Cached and encrypted infrastructure credentials found.
    Otto will now ask you for the password to decrypt these
    credentials.

Encrypted Credentials Password
  Infrastructure credentials are required for this operation. Otto found
  saved credentials that are password protected. Please enter the password
  to decrypt these credentials. You may also just hit <enter> and leave
  the password blank to force Otto to ask for the credentials again.

  Enter a value:
==> Querying infrastructure data for build...
==> Building deployment archive...
==> Building deployment artifact with Packer...
    Raw Packer output will begin streaming in below. Otto
    does not create this output. It is mirrored directly from
    Packer while the build is being run.

otto output will be in this color.

==> otto: Prevalidating AMI Name...
==> otto: Inspecting the source AMI...
==> otto: Creating temporary keypair: packer 564fbe7a-4174-8a3d-e509-7698f981cf07
==> otto: Creating temporary security group for this instance...
==> otto: VPCIdNotSpecified: No default VPC for this user
==> otto: 	status code: 400, request id: []
==> otto: Deleting temporary keypair...
Build 'otto' errored: VPCIdNotSpecified: No default VPC for this user
	status code: 400, request id: []
Error building app: Error executing Packer: exit status 1

The error messages from Packer are usually very informative.
Please read it carefully and fix any issues it mentions. If
the message isn't clear, please report this to the Otto project.
````

**Comment by justincampbell** [comment] 2015-12-01 16:48
I believe the issue reported by @njdevils9 and commented on by @joshRpowell are a duplicate of #235. Closing this in favor of that.

@themccallister I think your log output suggests a different issue. Would you mind opening a new issue with more information? It appears to be an error in the PHP `otto build` step.

**Closed by justincampbell** 2015-12-01 16:48 UTC
